# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Writing About Literature
tagline:             'Making/Writing Things in the 21st Century'
description:         'An in-progress course site for Fall 2019.'
url:                 ''
baseurl:             '/e107v3'
paginate:            5


# About/contact
author:
  name:              Jason Loan
  url:               https://twitter.com/loanage
  email:             jloan@pierce.ctc.edu

# Custom vars
version:             1.0.0

# This will require each of these plugins automatically.
plugins:
  - jekyll-paginate